name: CI workflow (przeplyw pracy CI)
on:
  push:
  pull_request:
  issues:
    types: [opened]

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run own composite action (uruchom moją własną akcję złożoną)
        id: my-action
        uses: ./
        with:
          who-to-greet: "@gesiud"

      - name: Output the answer (wypisz odpowiedź)
        run: echo "Odpowiedź to ${{ steps.my-action.outputs.answer }}"

      - name: test akcji 2
        uses: ./action-2
        with:
          user: "@gesiud"

      - name: test akcji 3
        uses: ./action-3
        with:
          who-to-greet: "@gesiud"
