name: issue-ops

on:
  issues:
    types: [labeled]

jobs:
  issue-ops:
    if: ${{ github.event.label.name == 'repo-request'}}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    outputs:
      REPO_NAME: ${{ steps.repo-request.outputs.REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0

      - name: Repository Request Validation
        id: repo-request
        env:
          GH_TOKEN: ${{ github.token}}
        run: |
          repo_name=$(echo '${{ steps.parse.outputs.data }}' | jq -r '.name.text')
          repo_dept=$(echo '${{ steps.parse.outputs.data}}' | jq -r '.departament.text')
          repo_full_name=$repo_dept-$repo_name
          echo "REPO_NAME=$repo_full_name" >> "$GITHUB_OUTPUT"

          mention="@${{ github.event.issue.user.login }}"
          message="Request repository '$repo_full_name' will be sent to approval."
          exitcode=0

          # nazwa nie moze byc pusta
          if [ -z "$repo_full_name" ]; then
            message="Repository name is empty."
            exitcode=1
          fi

          # nazwa repository powinna zawierac tylko znaki alfanumeryczne oraz znak minus
          if [[ "$repo_full_name" =~ [^a-zA-Z0-9-] ]]; then
            message="Repository name shall be alphanumeric and minus only"
            exitcode=1
          fi

          if [ $exitcode -ne 0 ]; then
            gh issue edit ${{ github.event.issue.number }} --remove-label repo-request
            message="$message Please fix the issue and try again by applying the label 'repo-request' again to that issue"
          fi

          gh issue comment ${{ github.event.issue.number }} -b "$mention $message"

          exit $exitcode

  create-repo:
    needs: issue-ops
    runs-on: ubuntu-latest
    environment: repo-creation
    permissions:
      issues: write
      contents: read
    env:
      REPO_OWNER: ${{ vars.ORGANISATION }}
      REPO_NAME: ${{ needs.issue-ops.outputs.REPO_NAME}}
      USER: ${{ github.event.issue.user.login }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}

    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v1.6.2
        id: get-workflow-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ vars.ORGANISATION }}

      - name: Create repository
        id: create-repo
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
        run: |
          REPO_URL=$(gh repo create $REPO_OWNER/$REPO_NAME --private --clone)
          echo "repo_url=$REPO_URL" >> "$GITHUB_OUTPUT"
          echo "Repository '$REPO_NAME' has been successfuly created: $REPO_URL"

      - name: Notify user
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_URL: ${{ steps.create-repo.outputs.repo_url }}
        run: |
          gh issue comment $ISSUE_NUMBER \
          -b "@$USER: Repository '$REPO_OWNER?REPO_NAME' has been created sucessfully: $REPO_URL" \
          --repo ${{ github.event.repository.full_name }}

      - name: Handle Exception
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment $ISSUE_NUMBER \
          -b '@$USER: Repository '$REPO_OWNER/$REPO_NAME' creation failed. Please contact the administrator' \
          -- repo ${{ github.event.repository.full_name }}
